### ISSUE TITLE
AudioCache player playing previous cached files, surround echo sound

### ISSUE THREAD

**Issue by dark-chocolate** [luanpotter/audioplayer#61]
I am using following method when a button is pressed, 

  ```
  AudioCache player = AudioCache(prefix: "audio/"); // this is member variable

  void _playFile() {
    player.clearCache();
    player.play("myFile.mp3");
  }
```

When I hit button say 5 times, I can hear the surrounded echo sound that means the player is still playing previous files, where it is supposed to only play fresh files. Am I doing something wrong?

**Comment by luanpotter** [comment]
Hi, @dark-chocolate! That's expected behavior of AudioCache, the idea is to play audios independently. If you want to play only one per time, i.e., stop the previous one before the next, there is a couple of ways you can do it!

1. The easy one is to set a fixedPlayer to the AudioCache, with the release mode set to STOP. That way, the cache will use the same player every time, therefore overwriting the current song and stopping the previous. The release mode = STOP will ensure that it will never release the resources associated with the media, allowing you to quickly resume later. If you have a lot of different sounds, consider the RELEASE option.

2. A more fine grained option, that's also harder, is that the play method actually returns the newly created AudioPlayer, so you can call stop yourself in it when you want. But for your use case, consider option 1. à priori, and only if you need more complex behavior, you can create a new Player every time but save the reference to control it later.

Hope this clears it up! If you have any more questions, please let me know! I hope that you are having a good time with audioplayers!

**Comment by dark-chocolate** [comment]
Thanks @luanpotter for your response, can you also provide me the code for the option-1? I got the idea but don't know how to implement that using code.

**Comment by luanpotter** [comment]
I can't test it right now, but something like this should work:

```dart
// create this only once
AudioCache player = AudioCache(prefix: "audio/", fixedPlayer: new AudioPlayer()
        ..setReleaseMode(ReleaseMode.STOP));

// somewhere else
player.play("myFile.mp3");
```

Also, you don't need to call clearCache, that's killing the propose of the AudioCache! Probably you wanted to stop playing previous audios, but what it does is it releases every resource, so every time you call play it will be needed to be fetch again.

The idea of AudioCache is to allow for caching a few sounds and quickly playing them on demand, either simultaneously (without fixedPlayer) or one at a time (with fixedPlayer).

Hope this helps!

**Comment by dark-chocolate** [comment]
Thanks 👍
