### ISSUE TITLE
AudioPlayer blocks UI on Andorid

### ISSUE THREAD

**Issue by the4thfloor** [luanpotter/audioplayer#7]
The call to prepare() can take a long time to execute, because it might involve fetching and decoding media data. So, as is the case with any method that may take long to execute, you should never call it from your application's UI thread.

https://developer.android.com/guide/topics/media/mediaplayer.html#preparingasync

**Comment by luanpotter** [comment]
Thanks for pointing it out, @the4thfloor ! Duly noted!

Indeed this needs to be fixed in the pursuit of a better user experience for audioplayers (and flame games).

I'm guessing just popping a new Thread and calling `prepare()` there should do the trick, but my knowledge of Android is not yet absolutely mastered, so I don't know if that's the best and most elegant solution.

Would you like to submit a PR?

**Comment by the4thfloor** [comment]
I created a PR (https://github.com/luanpotter/audioplayer/pull/8)
it is a little bit more than expected :-(

**Comment by luanpotter** [comment]
Released on `0.5.0`
